config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    resources :comments, except: [:show, :index]
  end

  resources :comments do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  has_many :comments, dependent: :destroy, as: :commentable

  validates :user, :body, presence: true

  def post
    return @post if defined?(@post)
    @post = commentable.is_a?(Post) ? commentable : commentable.post
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy, as: :commentable

  validates :text, presence: true
  validates :title, length: { minimum: 2, maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_commentable

  def new
    @comment = Comment.new
  end

  def create
    @comment = @commentable.comments.build(comment_params)

    if @comment.save
      respond_to do |format|
        format.html { redirect_to post_path(@comment.post), :notice => 'Comment saved!' }
        format.js
      end

    else
      render 'new'
    end

  end

  def edit
    @comment = @commentable.comments.find(params[:id])
  end

  def update
    @comment = @commentable.comments.find(params[:id])
    if @comment.update_attributes(comment_params)
      flash[:notice] = "Comment updated!"
      redirect_to post_path(@commentable)
    else
      render 'edit'
    end
  end

  def destroy
    @comment = @commentable.comments.find(params[:id])
    @comment.destroy
    flash[:alert] = "Comment deleted!"
    redirect_to post_path(@comment.post)
  end

  private

  def comment_params
    params.require(:comment).permit(:user, :body)
  end

  def find_commentable
    @commentable = Post.find(params[:post_id]) if params[:post_id]
    @commentable = Comment.find(params[:comment_id]) if params[:comment_id]

    redirect_to root_path unless defined?(@commentable)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Post created!"
      redirect_to root_path
    else
      flash[:alert] = @post.errors
      render 'new'
    end
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new(post_id: @post.id)
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:notice] = "Post updated!"
      redirect_to post_path
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:alert] = "Post deleted!"
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_comments_count(post)
    Post.find(post.id).comments.count
  end
end

app/views/comments/_comment.html.erb
<dl class="dl-horizontal">
  <hr>
  <dt><%= comment.user %></dt>
  <dd><%= comment.body %></dd>
  <% if comment.commentable.is_a?(Post) %>
    <dd>
      <%= link_to edit_post_comment_path(post_id: comment.commentable_id, id: comment.id) do %>
        <i class="glyphicon glyphicon-pencil"></i>
      <% end %>
      <%= link_to post_comment_path(post_id: comment.commentable_id, id: comment.id), method: :delete do %>
        <i class="glyphicon glyphicon-trash"></i>
      <% end %>
      <%= link_to '#', id: "reply-form-link", remote: true do %>
        <i class="fa fa-reply" aria-hidden="true"></i>
      <% end %>
    </dd>
  <% elsif comment.commentable.is_a?(Comment) %>
    <dd>
      <%= link_to edit_comment_comment_path(comment_id: comment.commentable_id, id: comment.id) do %>
        <i class="glyphicon glyphicon-pencil"></i>
      <% end %>
      <%= link_to comment_comment_path(comment_id: comment.commentable_id, id: comment.id), method: :delete do %>
        <i class="glyphicon glyphicon-trash"></i>
      <% end %>
      <%= link_to '#', id: "reply-form-link", remote: true do %>
        <i class="fa fa-reply" aria-hidden="true"></i>
      <% end %>
    </dd>
  <% end %>
  <br>
  <dd id="reply-form">
    <%= form_for [comment, Comment.new], remote: true do |f| %>
      <%= f.text_field :user, placeholder: "Commenter" %><br/>
      <%= f.text_area :body, placeholder: "Add a Reply" %><br/>
      <%= f.submit "Reply"  %>
    <% end %>
  </dd>
</dl>

<ul id="tests">
  <%= render partial: 'comments/comment', collection: comment.comments %>
</ul>

app/views/comments/_form.html.erb
<%= form_for ([@commentable, @comment]) do |f| %>

  <%= render "shared/error_messages", :target => @comment %>

  <div class="form-group">
    <%= f.label :user %>
    <%= f.text_field :user, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :comment %>
    <%= f.text_area :body, rows:3, class: "form-control"%>
  </div>

  <%= f.submit class: "btn btn-default" %>

<% end %>

app/views/comments/create.js.erb
$('#tests').append("<%= j render @comment %>");
$("#reply-form > #comment_body").val("");

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>

<%= render 'form' %>

app/views/comments/new.html.erb
<h1>Comments#new</h1>

<h2>Add a comment: </h2>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnRailsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <div id="main-container" class="container">
        <div class="row">
          <%= link_to "Home", root_path %>
        </div>
        <div class="row">
          <div class="col-xs-9">
            <%= yield %>
          </div>
        </div>
      </div>

    </body>

</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

  <%= render "shared/error_messages", :target => @post %>

  <div class="form-group">
    <%= f.label :post_title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :post_text %>
    <%= f.text_area :text, rows:15, class: "form-control"%>
  </div>

  <%= f.submit class: "btn btn-default" %>

<% end %>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Posts#index</h1>

<p><%= link_to "Add new post", new_post_path %></p>
<% @posts.each do |post| %>
<div class="row">
  <div class="col-md-12"><h3><%= link_to post.title, post_path(post) %> </h3></div>
</div>
<div class="row">
  <div class="col-md-12"><p><%= post.text %></p></div>
</div>
<div class="row">
  <div class="col-md-1">
    <%= link_to edit_post_path(post) do %>
      <i class="glyphicon glyphicon-pencil"></i>
    <% end %>
  </div>
  <div class="col-md-1">
    <%= link_to post, method: :delete do %>
      <i class="glyphicon glyphicon-trash"></i>
    <% end %>
  </div>
  <div class="col-md-4"><%= link_to "Add a comment", new_post_comment_path(post) %> </div>
</div>
<br>

<% end %>

app/views/posts/new.html.erb
<h1>Posts#new</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>

<div class="row">
  <div class="col-md-12">
    <h1><%= @post.title %></h1>
  </div>
  <div class="col-md-10">
    <p><%= @post.text %></p>
  </div>
  <div class="col-md-2" style="padding:0px">
    <div class="short-div">
      <%= link_to edit_post_path(@post) do %>
        <i class="glyphicon glyphicon-pencil"></i>
      <% end %>
    </div>
    <div class="short-div">
      <%= link_to @post, method: :delete do %>
        <i class="glyphicon glyphicon-trash"></i>
      <% end %>
    </div>
  </div>
</div>
<br>

<%= form_for [@post, Comment.new] do |f| %>
  <%= f.text_field :user, placeholder: "Commenter" %><br/>
  <%= f.text_area :body, placeholder: "Add a comment" %><br/>
  <%= f.submit "Add Comment" %>
<% end %>

<br>

<%= render(partial: 'comments/comment', collection: @post.comments.order(created_at: :desc)) %>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
<div class="error_explanation">
  <h2><%= pluralize(target.errors.count, "error") %> prevented this record from being saved:</h2>
  <ul>
  <% target.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>